export enum Paths {
    Login = '/login',
    Home = '/',
    Settings = '/settings',
    Characters = '/characters',
    Stats = '/stats',
    Skills = '/skills',
    Gear = '/gear',
    Feats = '/feats',
    SpecialAbilities = '/special-abilities',
    Images = '/images',
    NewCharacter='/new-character',
    Chapters='/chapters',
    NewChapter='/new-chapter',
    Map='/map',
    Users='/users',
    NewUser='/new-user',
    Account='/account',
    AccountCharacter='/my-character',
}